### ISSUE TITLE
Create npm package

### ISSUE THREAD

**Issue by bhackett1024** [RecordReplay/recordings-cli#1]
We should add an NPM package to make it simple to install the CLI tool, and update the README with installation instructions.

**Comment by jasonLaster** [comment]
One option is to use `replayio` which i snagged recently

https://github.com/RecordReplay/replayio
https://www.npmjs.com/package/replayio

I think the folks who are using `replay` would also be open as well to transferring it https://www.npmjs.com/package/replay

**Comment by bhackett1024** [comment]
We can reevaluate in the future but this feels like bikeshedding.  Using the existing recordreplay space like we do with our other npm packages is fine, we just need to actually go through the steps to publish this (which I don't know how to do).

**Comment by bhackett1024** [comment]
The npm package has been set up: https://www.npmjs.com/package/@recordreplay/recordings-cli
